### PR TITLE
Added Version Check

### PR DESCRIPTION
**Pull request by FarazzShaikh**
# Version Check (#8)
Added version check with customizable frequency

Screen Shot 2021-01-24 at 7 39 52 PM

Will get latest version from [NPM](https://registry.npmjs.org/sync-fork/latest) and prompt user to update if current version does not match latest.

PS: Will only prompt is current != latest or run with DEBUG flag.

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
Indeed it turned out the http route was faster (http: ~400ms - npm: ~2s). So i used that way of getting the latest and read current version from `package.json`. Please review.

**Comment by Andrew-Colman** [comment]
Looks amazing, very quality work 

just fixed one issue (the minified (build) version doesn't support dynamic requires)
also: fixed the path for cache, added it to be in global packages folder (don't want to conflict/overwrite possible local files in the user repository)

soon I'll extend it (add a --check command) , and remove boxen (as it has 8 additional dependencies) 
the promise of this package is to be small/fast and with less dependencies possible (I'll make a func to generate the box)

testable with: `npx sync-fork@0.2.0-dev`
I'll release it as **0.6.0** 

thanks a lot!

**Comment by FarazzShaikh** [comment]
Sure, I will fix those issues up and clean up the code a bit. By dynamic require do you simply mean moving my requires to the top of the file? If you can open an issue I'll make a PR

I actually liked working with this codebase, I'll close any other issues I can. 😄

**Comment by Andrew-Colman** [comment]
> Sure, I will fix those issues up and clean up the code a bit. If you can open an issue I'll make a PR

I fixed it here: https://github.com/Andrew-Colman/sync-fork/commit/ab57a064822ce599c9711a0de1fcfce20b626909

> By dynamic require do you simply mean moving my requires to the top of the file? 

https://github.com/Andrew-Colman/sync-fork/pull/15/files#diff-5dfe38baf287dcf756a17c2dd63483781b53bf4b669e10efdd01e74bcd8e780aL146
using require inside a function argument 

> I actually liked working with this codebase, I'll close any other issues I can. 😄

sounds great 😄

**Pull request merged**
