### PR TITLE
Added Automatic Conflict Resolution

### PR DESCRIPTION
**Pull request by FarazzShaikh**
### Added
- --upcoming (-U)
- --local (-L)
- --reset (-R)

### Notes
Must test the three added flags with some dummy repository.

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
I have no idea why it is trying to merge commits merged yesterday for #14. I synced my fork using it before making commits for this PR, maybe that messed something up?

**Comment by Andrew-Colman** [comment]
>Must test the three added flags with some dummy repository.

I use this alot: https://github.com/studiopen/dummy-sync2

>I have no idea why it is trying to merge commits merged yesterday

maybe creating feature branches could help, and leaving master just to sync

try: `git rebase -i HEAD~9` and drop the old commits

**Comment by FarazzShaikh** [comment]
>maybe creating feature branches could help, and leaving master just to sync
>
> try: git rebase -i HEAD~9 and drop the old commits

Alright i will try to sort it out and test if it works. Any changes you want me to make to the way --reset works?

**Comment by Andrew-Colman** [comment]
> > maybe creating feature branches could help, and leaving master just to sync
> > try: git rebase -i HEAD~9 and drop the old commits
> 
> Alright i will try to sort it out and test if it works. Any changes you want me to make to the way --reset works?

we need to add this before: checkoutCommand & fetchCommand
**resetCmd**
we need to add this after :` git push -f` 

the pathspec match for wrong branch name isn't working too:

**stderr** (Error) :
```
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.
```

**Comment by FarazzShaikh** [comment]
Alright will look into it.

**Comment by FarazzShaikh** [comment]
I have tested --reset using the dummy repository and it successfully resets to upstream.

**Comment by Andrew-Colman** [comment]
looks great, I'll need to fix some things and then merge it

**Comment by Andrew-Colman** [comment]
@FarazzShaikh I'll remove local and upcoming: it has a lot of unpredictable results:
- creating new commits automatically 
- users can run by accident and lose important changes 

I tried a lot to make it consistent but decided to stay only with reset and let them resolve complex conflicts manually

**Comment by FarazzShaikh** [comment]
Yes that makes sense. I will try to port the routine that makes the box from boxen to remove the dependencies.

**Pull request merged**
